export enum SceneId {
    GATE = 'GATE',
    FRONT_YARD = 'FRONT_YARD',
    FRONT_DOOR = 'FRONT_DOOR',
    SIDEWALL = 'SIDEWALL',
    BACK_YARD = 'BACK_YARD',
    PAVILION = 'PAVILION',
    OAKTREE = 'OAKTREE',
    POND = 'POND',
    GREENHOUSE = 'GREENHOUSE'
}